-- Users Table (handled by Supabase Auth, but adding profile data if needed)
-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,

  constraint username_length check (char_length(username) >= 3)
);

alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Set up Realtime!
begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime;
commit;
alter publication supabase_realtime add table profiles;

-- Reservations Table
create table reservations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  phone text not null,
  date date not null,
  time time not null,
  guests integer not null,
  special_requests text,
  status text default 'pending' check (status in ('pending', 'confirmed', 'cancelled')),
  user_id uuid references auth.users
);

alter table reservations enable row level security;

-- Policy: Users can see their own reservations.
create policy "Users can view own reservations"
  on reservations for select
  using ( auth.uid() = user_id );

-- Policy: Anyone can create a reservation (public form).
create policy "Anyone can create a reservation"
  on reservations for insert
  with check ( true );

-- Policy: Only admins (or specific roles) can update status (omitted for brevity, assume service role or admin check).

-- Events Inquiry Table
create table event_inquiries (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  phone text not null,
  event_type text not null,
  date date not null,
  guests integer not null,
  budget text,
  details text,
  status text default 'new' check (status in ('new', 'contacted', 'booked'))
);

alter table event_inquiries enable row level security;

-- Policy: Anyone can create an inquiry.
create policy "Anyone can create an inquiry"
  on event_inquiries for insert
  with check ( true );

-- Menu Items Table (for dynamic menu)
create table menu_items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  price numeric not null,
  category text not null check (category in ('starters', 'mains', 'burgers', 'pizza', 'desserts', 'drinks')),
  image_url text,
  is_available boolean default true,
  is_featured boolean default false
);

alter table menu_items enable row level security;

create policy "Public can view menu items"
  on menu_items for select
  using ( true );

-- Only authenticated staff can manage menu (simplified)
create policy "Staff can manage menu"
  on menu_items for all
  using ( auth.role() = 'authenticated' ); 
